
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: fi
      POSTGRES_USER: fi_user
      POSTGRES_PASSWORD: fi_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
