
services:
  postgres:
    image: postgres:14
    container_name: fi_db
    restart: always
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: fi_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
        - postgres
    env_file:
      - .env

volumes:
  postgres_data:
